###############################################################################:
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: test2-mariadb
      working_dir: /test-app
      volumes:
        - ./test:/test-app
        - ./db:/var/lib/mysql
      environment:
              #- MYSQL_HOST=localhost
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=rootpwd
          - MYSQL_DATABASE=TEST
      ports:
        - "8806:3306"

    webserver:
      image: nginx:alpine
      container_name: test2-webserver
      working_dir: /test-app
      volumes:
          - ./test:/test-app
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

      ports:
       - "8080:80"
      links:
       - php-fpm

    php-fpm:
      build: phpdocker/php-fpm
      container_name: test2-php-fpm
      working_dir: /test-app
      volumes:
        - ./test:/test-app
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
      links:
        - mariadb
